# Generated by Django 2.1.3 on 2019-01-04 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('desc', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Edu_experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('gra_school', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Job_experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('company', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Pro_experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('company', models.CharField(max_length=50)),
                ('job', models.CharField(max_length=100)),
                ('job_desc', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('1', '男'), ('0', '女')], max_length=2)),
                ('age', models.IntegerField(default=0)),
                ('edu', models.CharField(choices=[('1', '专科'), ('2', '本科'), ('3', '硕士'), ('4', '博士')], max_length=10)),
                ('self_assessment', models.CharField(max_length=200)),
                ('gra_date', models.DateTimeField()),
                ('phone_number', models.CharField(max_length=100)),
                ('mail', models.CharField(max_length=100)),
                ('profession', models.CharField(max_length=100)),
                ('edu_experience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Edu_experience')),
                ('job_experience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Job_experience')),
                ('pro_experience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Pro_experience')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('1', '男'), ('0', '女')], max_length=2)),
                ('signature', models.CharField(max_length=200)),
                ('resume', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='polls.Resume')),
            ],
        ),
        migrations.RemoveField(
            model_name='choice',
            name='question',
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
