# Generated by Django 2.1.3 on 2019-01-04 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20190104_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edu_experience',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='edu_experience',
            name='start_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='job_experience',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='job_experience',
            name='start_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='pro_experience',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='pro_experience',
            name='start_date',
            field=models.DateField(),
        ),
        migrations.RemoveField(
            model_name='resume',
            name='edu_experience',
        ),
        migrations.AddField(
            model_name='resume',
            name='edu_experience',
            field=models.ManyToManyField(to='polls.Edu_experience'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='gra_date',
            field=models.DateField(),
        ),
        migrations.RemoveField(
            model_name='resume',
            name='job_experience',
        ),
        migrations.AddField(
            model_name='resume',
            name='job_experience',
            field=models.ManyToManyField(to='polls.Job_experience'),
        ),
        migrations.RemoveField(
            model_name='resume',
            name='pro_experience',
        ),
        migrations.AddField(
            model_name='resume',
            name='pro_experience',
            field=models.ManyToManyField(to='polls.Pro_experience'),
        ),
    ]
