# Generated by Django 2.1.3 on 2019-01-04 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20190104_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edu_experience',
            name='end_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='edu_experience',
            name='start_date',
            field=models.DateTimeField(),
        ),
    ]
