# Generated by Django 2.1.3 on 2019-01-04 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20190104_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edu_experience',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='edu_experience',
            name='start_date',
            field=models.DateField(),
        ),
    ]
