# Generated by Django 2.1.3 on 2019-01-04 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20190104_1715'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='edu_experience',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='job_experience',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='pro_experience',
        ),
        migrations.AddField(
            model_name='edu_experience',
            name='resume',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='polls.Resume'),
        ),
        migrations.AddField(
            model_name='job_experience',
            name='resume',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='polls.Resume'),
        ),
        migrations.AddField(
            model_name='pro_experience',
            name='resume',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='polls.Resume'),
        ),
    ]
