# Generated by Django 2.1.2 on 2019-01-04 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_auto_20190104_1748'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job_position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_desc', models.CharField(max_length=300)),
                ('hr_name', models.CharField(max_length=50)),
                ('hr_phone', models.CharField(max_length=30)),
                ('hr_mail', models.CharField(default='', max_length=50)),
                ('edu_require', models.CharField(choices=[('1', '专科'), ('2', '本科'), ('3', '硕士'), ('4', '博士')], max_length=2)),
                ('pub_date', models.DateField(auto_now_add=True)),
                ('visits', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='company',
            name='address',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='job_position',
            name='company',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='polls.Company'),
        ),
    ]
