# Generated by Django 2.1.2 on 2019-01-04 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_auto_20190104_2254'),
    ]

    operations = [
        migrations.AddField(
            model_name='job_position',
            name='name',
            field=models.CharField(default='null', max_length=30),
        ),
    ]
