# Generated by Django 2.1.2 on 2019-01-05 13:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('polls', '0011_auto_20190105_1600'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(blank=True, choices=[('1', '男'), ('2', '女')], max_length=2, verbose_name='性别')),
                ('signature', models.CharField(blank=True, max_length=200, verbose_name='个性签名')),
                ('user_type', models.CharField(choices=[('1', '企业用户'), ('2', '学生用户')], max_length=10, verbose_name='用户类型')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='job_position',
            name='company',
        ),
    ]
