# Generated by Django 2.1.2 on 2019-01-06 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0012_auto_20190105_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('1', '男'), ('2', '女'), ('3', '未填写')], default='3', max_length=2, verbose_name='性别'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='signature',
            field=models.CharField(blank=True, default='空空如也', max_length=200, verbose_name='个性签名'),
        ),
    ]
