# Generated by Django 2.1.2 on 2019-01-06 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0013_auto_20190106_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(choices=[('1', '学生用户'), ('2', '企业用户')], max_length=10, verbose_name='用户类型'),
        ),
    ]
