# Generated by Django 2.1.2 on 2019-01-06 02:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0014_auto_20190106_1045'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='owner',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='polls.UserProfile'),
        ),
    ]
