# Generated by Django 2.1.2 on 2019-02-17 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0015_resume_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='signature',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='联系方式'),
        ),
    ]
