# Generated by Django 2.1.2 on 2019-02-17 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0016_auto_20190217_1500'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='age',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='gra_date',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='mail',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='name',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='phone_number',
        ),
    ]
