# Generated by Django 2.1.2 on 2019-02-17 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0018_userprofile_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Company',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='owner',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.RemoveField(
            model_name='edu_experience',
            name='resume',
        ),
        migrations.RemoveField(
            model_name='job_experience',
            name='resume',
        ),
        migrations.RemoveField(
            model_name='pro_experience',
            name='resume',
        ),
        migrations.AddField(
            model_name='edu_experience',
            name='edu',
            field=models.CharField(choices=[('1', '专科'), ('2', '本科'), ('3', '硕士'), ('4', '博士')], default='1', max_length=10),
        ),
        migrations.AddField(
            model_name='edu_experience',
            name='owner',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='polls.UserProfile'),
        ),
        migrations.AddField(
            model_name='edu_experience',
            name='profession',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='job_experience',
            name='owner',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='polls.UserProfile'),
        ),
        migrations.AddField(
            model_name='pro_experience',
            name='owner',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='polls.UserProfile'),
        ),
        migrations.DeleteModel(
            name='Resume',
        ),
    ]
