# Generated by Django 2.1.2 on 2019-02-18 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0019_auto_20190217_1821'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pro_experience',
            old_name='job',
            new_name='job_name',
        ),
        migrations.RenameField(
            model_name='pro_experience',
            old_name='company',
            new_name='job_role',
        ),
    ]
