# Generated by Django 2.1.2 on 2019-02-19 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0020_auto_20190218_2326'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job_experience',
            name='company',
        ),
        migrations.AddField(
            model_name='job_experience',
            name='company_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='job_experience',
            name='industry',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='job_experience',
            name='job_desc',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='job_experience',
            name='job_role',
            field=models.CharField(default='', max_length=50),
        ),
    ]
