# Generated by Django 2.1.2 on 2019-02-21 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0021_auto_20190219_2307'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job_position',
            name='edu_require',
        ),
        migrations.RemoveField(
            model_name='job_position',
            name='visits',
        ),
        migrations.AddField(
            model_name='job_position',
            name='edu_requ',
            field=models.CharField(choices=[('1', '专科'), ('2', '本科'), ('3', '硕士'), ('4', '博士'), ('5', '不限')], default='5', max_length=2),
        ),
        migrations.AddField(
            model_name='job_position',
            name='exp_req',
            field=models.CharField(choices=[('1', '专科'), ('2', '本科'), ('3', '硕士'), ('4', '博士'), ('5', '不限')], default='1', max_length=2),
        ),
        migrations.AddField(
            model_name='job_position',
            name='pro_req',
            field=models.CharField(default='', max_length=500),
        ),
    ]
