# Generated by Django 2.1.2 on 2019-02-21 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0022_auto_20190221_2349'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job_position',
            name='hr_mail',
        ),
        migrations.RemoveField(
            model_name='job_position',
            name='hr_name',
        ),
        migrations.RemoveField(
            model_name='job_position',
            name='hr_phone',
        ),
        migrations.RemoveField(
            model_name='job_position',
            name='pro_req',
        ),
        migrations.AddField(
            model_name='job_position',
            name='hr',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='polls.UserProfile'),
        ),
        migrations.AlterField(
            model_name='job_position',
            name='exp_req',
            field=models.CharField(choices=[('1', '无'), ('2', '一年'), ('3', '两年'), ('4', '三年及以上')], default='1', max_length=2),
        ),
        migrations.AlterField(
            model_name='job_position',
            name='name',
            field=models.CharField(default='', max_length=30),
        ),
    ]
