# Generated by Django 2.1.2 on 2019-02-21 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0023_auto_20190222_0009'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job_position',
            name='edu_requ',
        ),
        migrations.AddField(
            model_name='job_position',
            name='edu_req',
            field=models.CharField(choices=[('1', '不限'), ('2', '专科'), ('3', '本科'), ('4', '硕士'), ('5', '博士')], default='5', max_length=2),
        ),
    ]
