# Generated by Django 2.1.2 on 2019-02-23 11:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('polls', '0024_auto_20190222_0032'),
    ]

    operations = [
        migrations.CreateModel(
            name='HRProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50, verbose_name='姓名')),
                ('gender', models.CharField(blank=True, choices=[('1', '男'), ('2', '女'), ('3', '未填写')], default='3', max_length=2, verbose_name='性别')),
                ('phone', models.CharField(blank=True, default='', max_length=200, verbose_name='联系方式')),
                ('company', models.CharField(default='', max_length=100, verbose_name='公司')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='HRProfile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='job_position',
            name='hr',
        ),
        migrations.AddField(
            model_name='job_position',
            name='city',
            field=models.CharField(default='所有', max_length=80),
        ),
        migrations.AddField(
            model_name='job_position',
            name='publisher',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='polls.HRProfile'),
        ),
    ]
