# Generated by Django 2.1.2 on 2019-02-23 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0025_auto_20190223_1908'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='user_type',
        ),
    ]
