# Generated by Django 2.1.2 on 2019-02-23 16:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0026_remove_userprofile_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='job_position',
            name='salary',
            field=models.IntegerField(default=0, verbose_name='薪资'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='StuProfile', to=settings.AUTH_USER_MODEL),
        ),
    ]
