# Generated by Django 2.1.2 on 2019-03-04 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0028_auto_20190304_2306'),
    ]

    operations = [
        migrations.CreateModel(
            name='SendResume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Job_position')),
                ('stu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.UserProfile')),
            ],
        ),
        migrations.AlterField(
            model_name='edu_experience',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.UserProfile'),
        ),
        migrations.AlterField(
            model_name='job_experience',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.UserProfile'),
        ),
        migrations.AlterField(
            model_name='pro_experience',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.UserProfile'),
        ),
    ]
