# Generated by Django 2.1.2 on 2019-03-09 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0029_auto_20190304_2307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job_position',
            name='job_desc',
            field=models.TextField(max_length=300, verbose_name='岗位描述'),
        ),
    ]
