# Generated by Django 2.1.2 on 2019-03-09 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0030_auto_20190309_1906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job_experience',
            name='job_desc',
            field=models.CharField(default='', max_length=500),
        ),
    ]
