# Generated by Django 2.1.2 on 2019-03-09 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0031_auto_20190309_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job_experience',
            name='job_desc',
            field=models.TextField(default='', max_length=600),
        ),
        migrations.AlterField(
            model_name='job_position',
            name='job_desc',
            field=models.TextField(max_length=600, verbose_name='岗位描述'),
        ),
        migrations.AlterField(
            model_name='pro_experience',
            name='job_desc',
            field=models.TextField(max_length=600),
        ),
    ]
