# Generated by Django 2.1.2 on 2019-03-10 03:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0036_company_img_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hrprofile',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Company'),
        ),
    ]
