# Generated by Django 2.1.2 on 2019-03-19 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0039_remove_company_img_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='financing',
            field=models.CharField(choices=[('0', '不限'), ('1', '未融资'), ('2', '天使轮'), ('3', 'A轮'), ('4', 'B轮'), ('5', 'C轮'), ('6', 'D轮及以上'), ('7', '已上市'), ('8', '不需要融资')], default='1', max_length=2, verbose_name='融资阶段'),
        ),
        migrations.AlterField(
            model_name='company',
            name='industry_type',
            field=models.CharField(choices=[('0', '不限'), ('1', '电子商务'), ('2', '游戏'), ('3', '媒体'), ('4', '广告营销'), ('5', '数据服务'), ('6', '医疗健康'), ('7', '生活服务'), ('8', 'O2O'), ('9', '旅游'), ('10', '分类信息'), ('11', '音乐视频阅读'), ('12', '在线教育'), ('13', '社交网络'), ('14', '人力资源服务'), ('15', '信息安全'), ('16', '智能硬件'), ('17', '移动互联网'), ('18', '互联网'), ('19', '计算机软件'), ('20', '通信/网络设备'), ('21', '广告/公关/会展'), ('22', '互联网金融'), ('23', '物流/仓储'), ('24', '贸易进出口'), ('25', '咨询'), ('26', '工程施工'), ('27', '汽车生产'), ('28', '其他行业')], default='1', max_length=2, verbose_name='行业类型'),
        ),
        migrations.AlterField(
            model_name='company',
            name='scale',
            field=models.CharField(choices=[('0', '不限'), ('1', '0-20人'), ('2', '20-99人'), ('3', '100-499人'), ('4', '500-999人'), ('5', '1000-9999人'), ('6', '10000人以上')], default='1', max_length=2, verbose_name='公司规模'),
        ),
    ]
