# Generated by Django 2.1.2 on 2019-03-31 11:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0042_auto_20190325_2231'),
    ]

    operations = [
        migrations.AddField(
            model_name='sendresume',
            name='time',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='发布时间'),
            preserve_default=False,
        ),
    ]
