# Generated by Django 2.1.2 on 2019-03-31 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0043_sendresume_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sendresume',
            name='sta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Job_position', verbose_name='岗位'),
        ),
        migrations.AlterField(
            model_name='sendresume',
            name='stu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.UserProfile', verbose_name='学生'),
        ),
        migrations.AlterField(
            model_name='sendresume',
            name='time',
            field=models.DateField(auto_now=True, verbose_name='发布时间'),
        ),
    ]
