# Generated by Django 2.1.2 on 2019-03-31 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0044_auto_20190331_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sendresume',
            name='time',
            field=models.DateField(auto_now_add=True, verbose_name='发布时间'),
        ),
    ]
