# Generated by Django 2.1.2 on 2019-04-14 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0045_auto_20190331_2004'),
    ]

    operations = [
        migrations.AddField(
            model_name='job_position',
            name='need',
            field=models.IntegerField(default=0, verbose_name='人数需求'),
        ),
    ]
