# Generated by Django 2.1.2 on 2019-04-14 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0046_job_position_need'),
    ]

    operations = [
        migrations.AddField(
            model_name='sendresume',
            name='is_employ',
            field=models.CharField(choices=[(1, '录取'), (2, '待考验')], default='1', max_length=2, verbose_name='录取情况'),
        ),
    ]
