# Generated by Django 2.1.2 on 2019-04-14 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0049_auto_20190414_1256'),
    ]

    operations = [
        migrations.AddField(
            model_name='sendresume',
            name='show',
            field=models.CharField(choices=[('1', '显示'), ('0', '隐藏')], default='1', max_length=2, verbose_name='显示在页面'),
        ),
    ]
