# Generated by Django 2.1.2 on 2019-04-14 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0050_sendresume_show'),
    ]

    operations = [
        migrations.AddField(
            model_name='job_position',
            name='reg_num',
            field=models.IntegerField(default=0, verbose_name='投递人数'),
        ),
    ]
