# Generated by Django 2.1.2 on 2019-04-14 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0051_job_position_reg_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hrprofile',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.Company'),
        ),
    ]
