# Generated by Django 2.1.2 on 2019-04-17 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0052_auto_20190414_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job_position',
            name='city',
            field=models.CharField(choices=[('0', '不限'), ('1', '北京'), ('2', '上海'), ('3', '广州'), ('4', '深圳'), ('5', '杭州'), ('6', '天津'), ('0', '西安'), ('0', '苏州'), ('0', '武汉'), ('0', '厦门'), ('0', '长沙'), ('0', '成都'), ('0', '不限')], default='0', max_length=2, verbose_name='就业城市'),
        ),
    ]
