# Generated by Django 2.1.2 on 2019-04-19 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0053_auto_20190417_2352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='city',
            field=models.CharField(choices=[('0', '不限'), ('1', '北京'), ('2', '上海'), ('3', '广州'), ('4', '深圳'), ('5', '杭州'), ('6', '天津'), ('7', '西安'), ('8', '苏州'), ('9', '武汉'), ('10', '厦门'), ('11', '长沙'), ('12', '成都'), ('13', '长春'), ('14', '重庆'), ('15', '济南'), ('16', '南京'), ('17', '青岛')], default='0', max_length=2, verbose_name='公司总部'),
        ),
        migrations.AlterField(
            model_name='company',
            name='desc',
            field=models.TextField(max_length=2000, verbose_name='公司简介'),
        ),
        migrations.AlterField(
            model_name='job_experience',
            name='job_desc',
            field=models.TextField(default='', max_length=2000),
        ),
        migrations.AlterField(
            model_name='job_position',
            name='city',
            field=models.CharField(choices=[('0', '不限'), ('1', '北京'), ('2', '上海'), ('3', '广州'), ('4', '深圳'), ('5', '杭州'), ('6', '天津'), ('7', '西安'), ('8', '苏州'), ('9', '武汉'), ('10', '厦门'), ('11', '长沙'), ('12', '成都'), ('13', '长春'), ('14', '重庆'), ('15', '济南'), ('16', '南京'), ('17', '青岛')], default='0', max_length=2, verbose_name='就业城市'),
        ),
        migrations.AlterField(
            model_name='job_position',
            name='job_desc',
            field=models.TextField(max_length=2000, verbose_name='岗位描述'),
        ),
        migrations.AlterField(
            model_name='pro_experience',
            name='job_desc',
            field=models.TextField(max_length=2000),
        ),
    ]
