# Generated by Django 2.1.2 on 2019-05-03 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0054_auto_20190419_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='sendresume',
            name='show_notify',
            field=models.CharField(choices=[('1', '显示'), ('0', '隐藏')], default='1', max_length=2, verbose_name='显示在消息中心'),
        ),
    ]
