# Generated by Django 2.1.2 on 2019-05-05 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0057_auto_20190505_2145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sendresume',
            name='check',
            field=models.CharField(choices=[('1', '已查看'), ('0', '未查看')], default='0', max_length=2, verbose_name='查看状态'),
        ),
    ]
